### ISSUE TITLE
Ensure physics

### ISSUE THREAD

**Issue by Chrinnoc** [flosch46/shrdlite-course-project#10]
We need a function to check if a proposed literal satisfies the physics of the world. For example a big ball may not be inside a small box. As of now, this passes through.

**Comment by JulianoLagana** [comment]
Good point. Should that be the role of the interpreter or the planner, though?

**Comment by Chrinnoc** [comment]
isPhysicallyFeasible(obj1:string,obj2:string,rel:string,state:WorldState):boolean

**Comment by Chrinnoc** [comment]
Solved via commit cbf7a09b26d11f482da30cb7ead516dae70b75c3
