### ISSUE TITLE
Fix the "put"-command bug.

### ISSUE THREAD

**Issue by Chrinnoc** [flosch46/shrdlite-course-project#26]
Jonatan said

> --- The "put" command

> Finally, There is one more part of the specification that you haven't included, but it's a bit obscure and not very easy to tell from the course webpage, plus it's hard to test properly before having a planner. It's the command (as in, possible value of cmd.command) "put". You should handle it correctly in the final project though.

> The grammar is a bit overlapping, since writing "move", "put" or "drop" in the utterance is considered to mean the same thing. "put a ball in a box" and "move a ball inside a box" are both parsed to a command with cmd.command="move".

> However, the grammar also allows the construction "move it inside a box" or "put it on the floor" or "drop it beside a table". Again move, put and drop are interchangeable, but these examples are all parsed to a command with cmd.command="put". The "overlap" I mentioned is this, that both "move" and "put" in the natural-language utterance can be parsed into either "move" or "put" commands.

> The meaning of a "put" command is that we should move the thing we're already holding. So what you need to is handle a third case in addition to "take"
(which has an Object but not a Location) and "move" (which has both an Object and a Location), namely "put" (which has only a location, and should consider the object currently held, if any, to be the Object).

> As I said, this is hard to test correctly before you have the planner, since you need to start in a state where the arm is holding something. You could modify the starting world state, or the dummy plan, but the easiest way is to get your own Planner running first.

**Comment by lindenhenrik** [comment]
Resolved prior to re-submission
