### ISSUE TITLE
When will we design the function that plans an interpretation?

### ISSUE THREAD

**Issue by JulianoLagana** [flosch46/shrdlite-course-project#4]

**Comment by JulianoLagana** [comment]
When will we design the function `planInterpretation()`?

**Comment by flosch46** [comment]
At our meeting tomorrow? ;)

**Comment by JulianoLagana** [comment]
@flosch46 I think this week's deadline regards only `interpretCommand(...)`. Am I wrong?

**Comment by JulianoLagana** [comment]
These two functions are cited in the readme file of the [original Schrdlite repo](https://github.com/ChalmersGU-AI-course/shrdlite-course-project)

**Comment by JulianoLagana** [comment]
Based on my conversation with @Chrinnoc, we'll implement that together with the extensions, before the final submission.
