### ISSUE TITLE
Implement searchEntity()

### ISSUE THREAD

**Issue by JulianoLagana** [flosch46/shrdlite-course-project#7]

**Comment by JulianoLagana** [comment]
Header
`searchEntity(e : Entity , ws : WorldState) : String[]`

**Comment by JulianoLagana** [comment]
Initial implementation is up: commit 2ab652d7c0bfc6268c249c1d8da9b9761ee4e53a

**Comment by Chrinnoc** [comment]
Is the import of Entity necessary in the beginning? Could have used Parser.Entity instead where applicable?

**Comment by JulianoLagana** [comment]
To be honest, I didn't even remember that I changed that. It might just be a typo, feel free to correct if you have the time.

**Comment by Chrinnoc** [comment]
Will do.
